name: data_fetch_job

# 毎日毎時 15 分に実行する（15 分に理由はない）
on:
  schedule:
    - cron: "15 * * * *"

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo run
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        run: cargo run
        working-directory: ./batch
      - name: git setting
        run: |
          git config --local user.email admin@yfuwasegu.com
          git config --local user.name lunain84
      - name: Commit files
        run: |
          git add -A
          git commit -m "fetched data"
          git pull
          git push
