name: next deploy job

# masterブランチにプッシュしたときjobsに記述した操作を行う
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    # ubuntu OS を仮想マシン上に用意する
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Node.js環境のセットアップを行う
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # package.jsonに基づき依存パッケージをインストールする
      - name: install
        run: npm install --frozen-lockfile
        working-directory: ./nextjs

      # Next.jsアプリをビルドする
      # プロジェクトルート直下に.nextディレクトリができる
      - name: build
        run: npm run build
        working-directory: ./nextjs

      # 静的なHTMLとしてNext.jsアプリを生成する
      # プロジェクトルート直下にoutディレクトリができる
      # そのなかに、HTMLファイル群と、それらが読み込むJSファイル群を収めた_nextディレクトリがある
      - name: export
        run: npm run export
        working-directory: ./nextjs

      # しかしGitHub Pagesの仕様として_から始まるディレクトリが見えず404となる
      # つまりHTMLからJSを読み込めない
      # これを回避するために.nojekyllファイルをoutディレクトリに作る
      - name: add nojekyll
        run: touch ./out/.nojekyll
        working-directory: ./nextjs

      - name: copy contributions.json
        run: cp ./public/contributions.json ./nextjs/out/contributions.json

      # gh-pagesブランチにoutディレクトリの中身をプッシュする
      # gh-pagesブランチは自動的に作成される
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
